spring:
  application:
    name: banque1_api

  datasource:
    url: jdbc:postgresql://localhost:5432/banque1_api_db
    username: alassane
    password: alou123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server: port:8080
